### GET all categories

GET http://localhost:8080/api/category

### GET all products

GET http://localhost:8080/api/product

### POST a new product

POST http://localhost:8080/api/product
Content-Type: application/json

{
  "id": "2",
  "title": "My first blog",
  "description": "This is my first blog",
  "ownerId": "1",
  "price": 100
}
